// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgMbLTnkTZjx21Lw8kHn3fp4RutKBARGE',
    appId: '1:948770165877:web:63d8d277c39b9b3337143c',
    messagingSenderId: '948770165877',
    projectId: 'flutter-project-format',
    authDomain: 'flutter-project-format.firebaseapp.com',
    storageBucket: 'flutter-project-format.appspot.com',
    measurementId: 'G-9WXYRD303C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwlmcXsl8K5eA3QljeLvY4TBqSlbeJkc',
    appId: '1:198103789978:android:0c2fb2eaa9c9cb438d4a23',
    messagingSenderId: '198103789978',
    projectId: 'testing-fed3b',
    storageBucket: 'testing-fed3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPWCZlnE6hZGmCwejVs6qnN5LdeJZ7E8I',
    appId: '1:198103789978:ios:b698bb3be2c7b66c8d4a23',
    messagingSenderId: '198103789978',
    projectId: 'testing-fed3b',
    storageBucket: 'testing-fed3b.firebasestorage.app',
    iosBundleId: 'com.flutter.project.format',
  );

}